### ISSUE TITLE
Git is tracking __pycache__

### ISSUE THREAD

**Issue by sjiang1** [COSC481W-2020Fall/cosc481w-581-2020-fall-stattracker#12]
Every time I run the program, the __pycache__ is modified and the changes are tracked in Git.
![image](https://user-images.githubusercontent.com/2203934/93390762-39393c80-f83c-11ea-99ec-ab5a7a1bff58.png)

A .gitignore file should be added into the repository so that __pycache__ is ignored by Git.

**Comment by acdpsn** [comment]
added pycache directory to gitignore
