### ISSUE TITLE
Create database

### ISSUE THREAD

**Issue by BeeProdigy** [COSC481W-2020Fall/cosc481w-581-2020-fall-stattracker#31]
We are currently using csv files for our API and decks, we want to move this to a database.
- [x] Create database for API and decks
- [x] Moving API and decks to database

--- Refer to [README](https://github.com/COSC481W-2020Fall/cosc481w-581-2020-fall-stattracker/blob/databaseDoc/README.md) at bottom in databaseDoc branch ---

Test Cases:

- [x] Have the API transferred to the database
- [x] Make a deck and transfer to database

**Comment by sjiang1** [comment]
> Make a deck and transfer to database

Do you mean that from the website, when the user makes a deck, it's going to be added to the database?

**Comment by BeeProdigy** [comment]
I think for now it's just going to import the csv files that are made when someone makes a deck.

**Comment by BeeProdigy** [comment]
https://github.com/COSC481W-2020Fall/cosc481w-581-2020-fall-stattracker/commit/1ee8e772ac68cb1c077f27a36bc9a7ec4ffe8d1b
