### ISSUE TITLE
More bug fixing

### ISSUE THREAD

**Issue by Ryoumi** [COSC481W-2020Fall/cosc481w-581-2020-fall-stattracker#78]
I am going to fix more bugs and make sure most of not all bugs are worked out this week.

- Entering invalid deck code on Data Input Page gets an internal server error
- Get more data added to the datatbase.
- In the DeckBuilder page the titles align text for the all-cards table appears to be aligned to the right while everything is aligned to the center.

**Comment by sjiang1** [comment]
This is too vague. You need to list all the specific bugs that you want to finish this week.
